backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: base_posts
    fields: &ref_0
      - label: Banner
        name: img
        widget: image
        required: false
      - label: Top
        name: top
        widget: boolean
        required: false
      - label: Cover
        name: cover
        widget: boolean
        required: false
      - label: Password
        name: password
        widget: number
        required: false
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: date
        required: false
        dateFormat: YYYY-MM-DD
        format: YYYY-MM-DD
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Keywords
        name: keywords
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
    label: 文章
    folder: source/_posts/base
    create: true
    editor:
      preview: true
  - name: notes_posts
    fields: *ref_0
    label: 笔记
    folder: source/_posts/notes
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: 404.md
        label: '404'
        file: source\404.md
        editor:
          preview: false
        fields: *ref_0
      - name: about-index.md
        label: about
        file: source\about\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: contact-index.md
        label: contact
        file: source\contact\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: categories-index.md
        label: categories
        file: source\categories\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: friends-index.md
        label: friends
        file: source\friends\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: galleries-index.md
        label: 相册
        file: source\galleries\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: tags-index.md
        label: tags
        file: source\tags\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: notes-index.md
        label: 笔记
        file: source\notes\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: galleries-blog-index.md
        label: blog
        file: source\galleries\blog\index.md
        editor:
          preview: false
        fields: *ref_0
      - name: galleries-private-index.md
        label: private
        file: source\galleries\private\index.md
        editor:
          preview: false
        fields: *ref_0
